# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/XADC_intr.xdc

# Block Designs: bd/XADC_intr/XADC_intr.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==XADC_intr || ORIG_REF_NAME==XADC_intr} -quiet] -quiet

# IP: bd/XADC_intr/ip/XADC_intr_processing_system7_0_0/XADC_intr_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==XADC_intr_processing_system7_0_0 || ORIG_REF_NAME==XADC_intr_processing_system7_0_0} -quiet] -quiet

# IP: bd/XADC_intr/ip/XADC_intr_xadc_wiz_0_0/XADC_intr_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==XADC_intr_xadc_wiz_0_0 || ORIG_REF_NAME==XADC_intr_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/XADC_intr/ip/XADC_intr_ps7_0_axi_periph_0/XADC_intr_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==XADC_intr_ps7_0_axi_periph_0 || ORIG_REF_NAME==XADC_intr_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/XADC_intr/ip/XADC_intr_rst_ps7_0_100M_0/XADC_intr_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==XADC_intr_rst_ps7_0_100M_0 || ORIG_REF_NAME==XADC_intr_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/XADC_intr/ip/XADC_intr_auto_pc_0/XADC_intr_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==XADC_intr_auto_pc_0 || ORIG_REF_NAME==XADC_intr_auto_pc_0} -quiet] -quiet

# XDC: bd/XADC_intr/XADC_intr_ooc.xdc
