# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/sebastian/Desktop/Git/EmbeddedSystems/XADC_intr/XADC_intr.cache/wt [current_project]
set_property parent.project_path /home/sebastian/Desktop/Git/EmbeddedSystems/XADC_intr/XADC_intr.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:2.0 [current_project]
set_property ip_output_repo /home/sebastian/Desktop/Git/EmbeddedSystems/XADC_intr/XADC_intr.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/sebastian/Desktop/Git/EmbeddedSystems/XADC_intr/XADC_intr.srcs/sources_1/bd/XADC_intr/hdl/XADC_intr_wrapper.v
add_files /home/sebastian/Desktop/Git/EmbeddedSystems/XADC_intr/XADC_intr.srcs/sources_1/bd/XADC_intr/XADC_intr.bd
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/XADC_intr/XADC_intr.srcs/sources_1/bd/XADC_intr/ip/XADC_intr_processing_system7_0_0/XADC_intr_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/XADC_intr/XADC_intr.srcs/sources_1/bd/XADC_intr/ip/XADC_intr_xadc_wiz_0_0/XADC_intr_xadc_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/XADC_intr/XADC_intr.srcs/sources_1/bd/XADC_intr/ip/XADC_intr_xadc_wiz_0_0/XADC_intr_xadc_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/XADC_intr/XADC_intr.srcs/sources_1/bd/XADC_intr/ip/XADC_intr_rst_ps7_0_100M_0/XADC_intr_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/XADC_intr/XADC_intr.srcs/sources_1/bd/XADC_intr/ip/XADC_intr_rst_ps7_0_100M_0/XADC_intr_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/XADC_intr/XADC_intr.srcs/sources_1/bd/XADC_intr/ip/XADC_intr_rst_ps7_0_100M_0/XADC_intr_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/XADC_intr/XADC_intr.srcs/sources_1/bd/XADC_intr/ip/XADC_intr_auto_pc_0/XADC_intr_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/XADC_intr/XADC_intr.srcs/sources_1/bd/XADC_intr/XADC_intr_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/sebastian/Desktop/Git/EmbeddedSystems/XADC_intr/XADC_intr.srcs/constrs_1/new/XADC_intr.xdc
set_property used_in_implementation false [get_files /home/sebastian/Desktop/Git/EmbeddedSystems/XADC_intr/XADC_intr.srcs/constrs_1/new/XADC_intr.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top XADC_intr_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef XADC_intr_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file XADC_intr_wrapper_utilization_synth.rpt -pb XADC_intr_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
