# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/RGB_Matrix.xdc

# Block Designs: bd/Lab5/Lab5.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab5 || ORIG_REF_NAME==Lab5} -quiet] -quiet

# IP: bd/Lab5/ip/Lab5_processing_system7_0_0/Lab5_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab5_processing_system7_0_0 || ORIG_REF_NAME==Lab5_processing_system7_0_0} -quiet] -quiet

# IP: bd/Lab5/ip/Lab5_blk_mem_gen_0_0/Lab5_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab5_blk_mem_gen_0_0 || ORIG_REF_NAME==Lab5_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/Lab5/ip/Lab5_axi_bram_ctrl_0_0/Lab5_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab5_axi_bram_ctrl_0_0 || ORIG_REF_NAME==Lab5_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/Lab5/ip/Lab5_axi_smc_0/Lab5_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab5_axi_smc_0 || ORIG_REF_NAME==Lab5_axi_smc_0} -quiet] -quiet

# IP: bd/Lab5/ip/Lab5_rst_ps7_0_100M_0/Lab5_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab5_rst_ps7_0_100M_0 || ORIG_REF_NAME==Lab5_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/Lab5/Lab5_ooc.xdc
