# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab3/Lab3.srcs/sources_1/bd/Lab3/ip/Lab3_blk_mem_gen_0_0/Lab3_blk_mem_gen_0_0.xci
# IP: The module: 'Lab3_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab3/Lab3.srcs/sources_1/bd/Lab3/ip/Lab3_blk_mem_gen_0_0/Lab3_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab3_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab3/Lab3.srcs/sources_1/bd/Lab3/ip/Lab3_blk_mem_gen_0_0/Lab3_blk_mem_gen_0_0.xci
# IP: The module: 'Lab3_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab3/Lab3.srcs/sources_1/bd/Lab3/ip/Lab3_blk_mem_gen_0_0/Lab3_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab3_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
