# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab6/Lab6.srcs/sources_1/bd/Lab6/ip/Lab6_processing_system7_0_0/Lab6_processing_system7_0_0.xci
# IP: The module: 'Lab6_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab6/Lab6.srcs/sources_1/bd/Lab6/ip/Lab6_processing_system7_0_0/Lab6_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab6_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab6/Lab6.srcs/sources_1/bd/Lab6/ip/Lab6_processing_system7_0_0/Lab6_processing_system7_0_0.xci
# IP: The module: 'Lab6_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab6/Lab6.srcs/sources_1/bd/Lab6/ip/Lab6_processing_system7_0_0/Lab6_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab6_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
