webtalk_init -webtalk_dir /home/sebastian/Desktop/Git/EmbeddedSystems/Linux_Test/Linux_Test.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2021-04-25 10:12:01" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "hik17ce9hrn7j238fhttijcief" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "963.538 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.225 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1619336827000" -context "sdk\\\\bsp/1619336827000"
webtalk_add_data -client sdk -key hwid -value "1617730414000" -context "sdk\\\\bsp/1619336827000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1619336827000"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\bsp/1619336827000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1619336827000"
webtalk_add_data -client sdk -key uid -value "1619336835000" -context "sdk\\\\application/1619336835000"
webtalk_add_data -client sdk -key hwid -value "1617730414000" -context "sdk\\\\application/1619336835000"
webtalk_add_data -client sdk -key bspid -value "1619336827000" -context "sdk\\\\application/1619336835000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1619336835000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1619336835000"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1619336835000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1619336835000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1619336835000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1619336835000"
webtalk_add_data -client sdk -key projSize -value "596.19140625" -context "sdk\\\\application/1619336835000"
webtalk_add_data -client sdk -key uid -value "1619336943000" -context "sdk\\\\bsp/1619336943000"
webtalk_add_data -client sdk -key hwid -value "1617730414000" -context "sdk\\\\bsp/1619336943000"
webtalk_add_data -client sdk -key os -value "device_tree" -context "sdk\\\\bsp/1619336943000"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1619336943000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1619336943000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1619338321669"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1619338321669"
webtalk_add_data -client sdk -key BootgenCount -value "2" -context "sdk\\\\bsp/1619338321669"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1619338321669"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1619338321669"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1619338321669"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1619338321669"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1619338321669"
webtalk_transmit -clientid 1487628723 -regid "" -xml /home/sebastian/Desktop/Git/EmbeddedSystems/Linux_Test/Linux_Test.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/sebastian/Desktop/Git/EmbeddedSystems/Linux_Test/Linux_Test.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/sebastian/Desktop/Git/EmbeddedSystems/Linux_Test/Linux_Test.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
