# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/RGB_Matrix.xdc

# Block Designs: bd/SpaceInvaders/SpaceInvaders.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SpaceInvaders || ORIG_REF_NAME==SpaceInvaders} -quiet] -quiet

# IP: bd/SpaceInvaders/ip/SpaceInvaders_xadc_wiz_0_0/SpaceInvaders_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SpaceInvaders_xadc_wiz_0_0 || ORIG_REF_NAME==SpaceInvaders_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/SpaceInvaders/ip/SpaceInvaders_blk_mem_gen_0_0/SpaceInvaders_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SpaceInvaders_blk_mem_gen_0_0 || ORIG_REF_NAME==SpaceInvaders_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/SpaceInvaders/ip/SpaceInvaders_blk_mem_gen_0_1/SpaceInvaders_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SpaceInvaders_blk_mem_gen_0_1 || ORIG_REF_NAME==SpaceInvaders_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/SpaceInvaders/ip/SpaceInvaders_axi_bram_ctrl_0_0/SpaceInvaders_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SpaceInvaders_axi_bram_ctrl_0_0 || ORIG_REF_NAME==SpaceInvaders_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/SpaceInvaders/ip/SpaceInvaders_axi_bram_ctrl_0_1/SpaceInvaders_axi_bram_ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SpaceInvaders_axi_bram_ctrl_0_1 || ORIG_REF_NAME==SpaceInvaders_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/SpaceInvaders/ip/SpaceInvaders_axi_gpio_0_0/SpaceInvaders_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SpaceInvaders_axi_gpio_0_0 || ORIG_REF_NAME==SpaceInvaders_axi_gpio_0_0} -quiet] -quiet

# IP: bd/SpaceInvaders/ip/SpaceInvaders_axi_gpio_0_1/SpaceInvaders_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SpaceInvaders_axi_gpio_0_1 || ORIG_REF_NAME==SpaceInvaders_axi_gpio_0_1} -quiet] -quiet

# IP: bd/SpaceInvaders/ip/SpaceInvaders_processing_system7_0_0/SpaceInvaders_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SpaceInvaders_processing_system7_0_0 || ORIG_REF_NAME==SpaceInvaders_processing_system7_0_0} -quiet] -quiet

# IP: bd/SpaceInvaders/ip/SpaceInvaders_microblaze_0_1/SpaceInvaders_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SpaceInvaders_microblaze_0_1 || ORIG_REF_NAME==SpaceInvaders_microblaze_0_1} -quiet] -quiet

# IP: bd/SpaceInvaders/ip/SpaceInvaders_dlmb_v10_2/SpaceInvaders_dlmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SpaceInvaders_dlmb_v10_2 || ORIG_REF_NAME==SpaceInvaders_dlmb_v10_2} -quiet] -quiet

# IP: bd/SpaceInvaders/ip/SpaceInvaders_ilmb_v10_2/SpaceInvaders_ilmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SpaceInvaders_ilmb_v10_2 || ORIG_REF_NAME==SpaceInvaders_ilmb_v10_2} -quiet] -quiet

# IP: bd/SpaceInvaders/ip/SpaceInvaders_dlmb_bram_if_cntlr_2/SpaceInvaders_dlmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SpaceInvaders_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==SpaceInvaders_dlmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/SpaceInvaders/ip/SpaceInvaders_ilmb_bram_if_cntlr_2/SpaceInvaders_ilmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SpaceInvaders_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==SpaceInvaders_ilmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/SpaceInvaders/ip/SpaceInvaders_lmb_bram_2/SpaceInvaders_lmb_bram_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SpaceInvaders_lmb_bram_2 || ORIG_REF_NAME==SpaceInvaders_lmb_bram_2} -quiet] -quiet

# IP: bd/SpaceInvaders/ip/SpaceInvaders_xbar_2/SpaceInvaders_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SpaceInvaders_xbar_2 || ORIG_REF_NAME==SpaceInvaders_xbar_2} -quiet] -quiet

# IP: bd/SpaceInvaders/ip/SpaceInvaders_microblaze_0_axi_periph_2/SpaceInvaders_microblaze_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SpaceInvaders_microblaze_0_axi_periph_2 || ORIG_REF_NAME==SpaceInvaders_microblaze_0_axi_periph_2} -quiet] -quiet

# IP: bd/SpaceInvaders/ip/SpaceInvaders_microblaze_0_axi_intc_2/SpaceInvaders_microblaze_0_axi_intc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SpaceInvaders_microblaze_0_axi_intc_2 || ORIG_REF_NAME==SpaceInvaders_microblaze_0_axi_intc_2} -quiet] -quiet

# IP: bd/SpaceInvaders/ip/SpaceInvaders_microblaze_0_xlconcat_2/SpaceInvaders_microblaze_0_xlconcat_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SpaceInvaders_microblaze_0_xlconcat_2 || ORIG_REF_NAME==SpaceInvaders_microblaze_0_xlconcat_2} -quiet] -quiet

# IP: bd/SpaceInvaders/ip/SpaceInvaders_mdm_1_2/SpaceInvaders_mdm_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SpaceInvaders_mdm_1_2 || ORIG_REF_NAME==SpaceInvaders_mdm_1_2} -quiet] -quiet

# IP: bd/SpaceInvaders/ip/SpaceInvaders_rst_ps7_0_100M_0/SpaceInvaders_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SpaceInvaders_rst_ps7_0_100M_0 || ORIG_REF_NAME==SpaceInvaders_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/SpaceInvaders/ip/SpaceInvaders_axi_bram_ctrl_2_1/SpaceInvaders_axi_bram_ctrl_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SpaceInvaders_axi_bram_ctrl_2_1 || ORIG_REF_NAME==SpaceInvaders_axi_bram_ctrl_2_1} -quiet] -quiet

# IP: bd/SpaceInvaders/ip/SpaceInvaders_axi_smc_1/SpaceInvaders_axi_smc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SpaceInvaders_axi_smc_1 || ORIG_REF_NAME==SpaceInvaders_axi_smc_1} -quiet] -quiet

# IP: bd/SpaceInvaders/ip/SpaceInvaders_auto_pc_0/SpaceInvaders_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SpaceInvaders_auto_pc_0 || ORIG_REF_NAME==SpaceInvaders_auto_pc_0} -quiet] -quiet

# IP: bd/SpaceInvaders/ip/SpaceInvaders_auto_pc_1/SpaceInvaders_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SpaceInvaders_auto_pc_1 || ORIG_REF_NAME==SpaceInvaders_auto_pc_1} -quiet] -quiet

# XDC: bd/SpaceInvaders/SpaceInvaders_ooc.xdc
