# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/IndividualProject_axi_smc_0.xci
# IP: The module: 'IndividualProject_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/bd_8718.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_0/bd_8718_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_1/bd_8718_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_2/bd_8718_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_3/bd_8718_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_4/bd_8718_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_5/bd_8718_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_6/bd_8718_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_7/bd_8718_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_8/bd_8718_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_9/bd_8718_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_10/bd_8718_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_11/bd_8718_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_12/bd_8718_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_13/bd_8718_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_14/bd_8718_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_15/bd_8718_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_16/bd_8718_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_17/bd_8718_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_18/bd_8718_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_19/bd_8718_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_20/bd_8718_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_21/bd_8718_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_22/bd_8718_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_23/bd_8718_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_24/bd_8718_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_25/bd_8718_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_26/bd_8718_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_27/bd_8718_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_28/bd_8718_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_29/bd_8718_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_30/bd_8718_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_31/bd_8718_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_32/bd_8718_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_33/bd_8718_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_34/bd_8718_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_35/bd_8718_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_36/bd_8718_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_37/bd_8718_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_38/bd_8718_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_39/bd_8718_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_40/bd_8718_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_41/bd_8718_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_42/bd_8718_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_43/bd_8718_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_44/bd_8718_m04s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_45/bd_8718_m04arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_46/bd_8718_m04rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_47/bd_8718_m04awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_48/bd_8718_m04wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_49/bd_8718_m04bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_50/bd_8718_m04e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IndividualProject_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_1/bd_8718_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_1/bd_8718_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_2/bd_8718_arsw_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_3/bd_8718_rsw_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_4/bd_8718_awsw_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_5/bd_8718_wsw_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_6/bd_8718_bsw_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_10/bd_8718_s00a2s_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_11/bd_8718_sarn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_12/bd_8718_srn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_13/bd_8718_sawn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_14/bd_8718_swn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_15/bd_8718_sbn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_16/bd_8718_m00s2a_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_17/bd_8718_m00arn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_18/bd_8718_m00rn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_19/bd_8718_m00awn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_20/bd_8718_m00wn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_21/bd_8718_m00bn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_23/bd_8718_m01s2a_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_24/bd_8718_m01arn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_25/bd_8718_m01rn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_26/bd_8718_m01awn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_27/bd_8718_m01wn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_28/bd_8718_m01bn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_30/bd_8718_m02s2a_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_31/bd_8718_m02arn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_32/bd_8718_m02rn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_33/bd_8718_m02awn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_34/bd_8718_m02wn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_35/bd_8718_m02bn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_37/bd_8718_m03s2a_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_38/bd_8718_m03arn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_39/bd_8718_m03rn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_40/bd_8718_m03awn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_41/bd_8718_m03wn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_42/bd_8718_m03bn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_44/bd_8718_m04s2a_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_45/bd_8718_m04arn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_46/bd_8718_m04rn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_47/bd_8718_m04awn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_48/bd_8718_m04wn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_49/bd_8718_m04bn_0_ooc.xdc

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/IndividualProject_axi_smc_0.xci
# IP: The module: 'IndividualProject_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/bd_8718.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_0/bd_8718_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_1/bd_8718_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_2/bd_8718_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_3/bd_8718_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_4/bd_8718_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_5/bd_8718_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_6/bd_8718_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_7/bd_8718_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_8/bd_8718_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_9/bd_8718_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_10/bd_8718_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_11/bd_8718_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_12/bd_8718_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_13/bd_8718_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_14/bd_8718_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_15/bd_8718_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_16/bd_8718_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_17/bd_8718_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_18/bd_8718_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_19/bd_8718_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_20/bd_8718_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_21/bd_8718_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_22/bd_8718_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_23/bd_8718_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_24/bd_8718_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_25/bd_8718_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_26/bd_8718_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_27/bd_8718_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_28/bd_8718_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_29/bd_8718_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_30/bd_8718_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_31/bd_8718_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_32/bd_8718_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_33/bd_8718_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_34/bd_8718_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_35/bd_8718_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_36/bd_8718_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_37/bd_8718_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_38/bd_8718_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_39/bd_8718_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_40/bd_8718_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_41/bd_8718_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_42/bd_8718_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_43/bd_8718_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_44/bd_8718_m04s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_45/bd_8718_m04arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_46/bd_8718_m04rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_47/bd_8718_m04awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_48/bd_8718_m04wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_49/bd_8718_m04bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_50/bd_8718_m04e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IndividualProject_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_1/bd_8718_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_1/bd_8718_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_2/bd_8718_arsw_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_3/bd_8718_rsw_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_4/bd_8718_awsw_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_5/bd_8718_wsw_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_6/bd_8718_bsw_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_10/bd_8718_s00a2s_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_11/bd_8718_sarn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_12/bd_8718_srn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_13/bd_8718_sawn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_14/bd_8718_swn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_15/bd_8718_sbn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_16/bd_8718_m00s2a_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_17/bd_8718_m00arn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_18/bd_8718_m00rn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_19/bd_8718_m00awn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_20/bd_8718_m00wn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_21/bd_8718_m00bn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_23/bd_8718_m01s2a_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_24/bd_8718_m01arn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_25/bd_8718_m01rn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_26/bd_8718_m01awn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_27/bd_8718_m01wn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_28/bd_8718_m01bn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_30/bd_8718_m02s2a_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_31/bd_8718_m02arn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_32/bd_8718_m02rn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_33/bd_8718_m02awn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_34/bd_8718_m02wn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_35/bd_8718_m02bn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_37/bd_8718_m03s2a_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_38/bd_8718_m03arn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_39/bd_8718_m03rn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_40/bd_8718_m03awn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_41/bd_8718_m03wn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_42/bd_8718_m03bn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_44/bd_8718_m04s2a_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_45/bd_8718_m04arn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_46/bd_8718_m04rn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_47/bd_8718_m04awn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_48/bd_8718_m04wn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_49/bd_8718_m04bn_0_ooc.xdc
