# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_xadc_wiz_0_1/IndividualProject_xadc_wiz_0_1.xci
# IP: The module: 'IndividualProject_xadc_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_xadc_wiz_0_1/IndividualProject_xadc_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IndividualProject_xadc_wiz_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_xadc_wiz_0_1/IndividualProject_xadc_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'IndividualProject_xadc_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_xadc_wiz_0_1/IndividualProject_xadc_wiz_0_1.xci
# IP: The module: 'IndividualProject_xadc_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_xadc_wiz_0_1/IndividualProject_xadc_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IndividualProject_xadc_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_xadc_wiz_0_1/IndividualProject_xadc_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'IndividualProject_xadc_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
