# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Linux_Test/Linux_Test.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Linux_Test || ORIG_REF_NAME==Linux_Test} -quiet] -quiet

# IP: bd/Linux_Test/ip/Linux_Test_processing_system7_0_0/Linux_Test_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Linux_Test_processing_system7_0_0 || ORIG_REF_NAME==Linux_Test_processing_system7_0_0} -quiet] -quiet

# IP: bd/Linux_Test/ip/Linux_Test_proc_sys_reset_0_0/Linux_Test_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Linux_Test_proc_sys_reset_0_0 || ORIG_REF_NAME==Linux_Test_proc_sys_reset_0_0} -quiet] -quiet

# XDC: bd/Linux_Test/Linux_Test_ooc.xdc
