# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/XADC_intr/XADC_intr.srcs/sources_1/bd/XADC_intr/ip/XADC_intr_xadc_wiz_0_0/XADC_intr_xadc_wiz_0_0.xci
# IP: The module: 'XADC_intr_xadc_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/XADC_intr/XADC_intr.srcs/sources_1/bd/XADC_intr/ip/XADC_intr_xadc_wiz_0_0/XADC_intr_xadc_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'XADC_intr_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/XADC_intr/XADC_intr.srcs/sources_1/bd/XADC_intr/ip/XADC_intr_xadc_wiz_0_0/XADC_intr_xadc_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'XADC_intr_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/XADC_intr/XADC_intr.srcs/sources_1/bd/XADC_intr/ip/XADC_intr_xadc_wiz_0_0/XADC_intr_xadc_wiz_0_0.xci
# IP: The module: 'XADC_intr_xadc_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/XADC_intr/XADC_intr.srcs/sources_1/bd/XADC_intr/ip/XADC_intr_xadc_wiz_0_0/XADC_intr_xadc_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'XADC_intr_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/XADC_intr/XADC_intr.srcs/sources_1/bd/XADC_intr/ip/XADC_intr_xadc_wiz_0_0/XADC_intr_xadc_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'XADC_intr_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
