webtalk_init -webtalk_dir /home/sebastian/Desktop/Git/EmbeddedSystems/Lecture4_Exercise1/Lecture4_Exercise1.sim/sim_1/behav/xsim/xsim.dir/stopwatch_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Feb 24 10:05:34 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3448ad7a-94e9-440c-9c5f-173032100532" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9338e9e4cb0d4bd785441f8f2d6fa382" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Linuxmint" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Linux Mint 20" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3166.970 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "0 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.14_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "114812_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1035294877 -regid "" -xml /home/sebastian/Desktop/Git/EmbeddedSystems/Lecture4_Exercise1/Lecture4_Exercise1.sim/sim_1/behav/xsim/xsim.dir/stopwatch_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/sebastian/Desktop/Git/EmbeddedSystems/Lecture4_Exercise1/Lecture4_Exercise1.sim/sim_1/behav/xsim/xsim.dir/stopwatch_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/sebastian/Desktop/Git/EmbeddedSystems/Lecture4_Exercise1/Lecture4_Exercise1.sim/sim_1/behav/xsim/xsim.dir/stopwatch_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
