# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/RGB_Matrix.xdc

# Block Designs: bd/Lab4_V2/Lab4_V2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab4_V2 || ORIG_REF_NAME==Lab4_V2} -quiet] -quiet

# IP: bd/Lab4_V2/ip/Lab4_V2_processing_system7_0_0/Lab4_V2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab4_V2_processing_system7_0_0 || ORIG_REF_NAME==Lab4_V2_processing_system7_0_0} -quiet] -quiet

# IP: bd/Lab4_V2/ip/Lab4_V2_blk_mem_gen_0_0/Lab4_V2_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab4_V2_blk_mem_gen_0_0 || ORIG_REF_NAME==Lab4_V2_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/Lab4_V2/ip/Lab4_V2_axi_bram_ctrl_0_0/Lab4_V2_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab4_V2_axi_bram_ctrl_0_0 || ORIG_REF_NAME==Lab4_V2_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/Lab4_V2/ip/Lab4_V2_axi_smc_0/Lab4_V2_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab4_V2_axi_smc_0 || ORIG_REF_NAME==Lab4_V2_axi_smc_0} -quiet] -quiet

# IP: bd/Lab4_V2/ip/Lab4_V2_rst_ps7_0_100M_0/Lab4_V2_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab4_V2_rst_ps7_0_100M_0 || ORIG_REF_NAME==Lab4_V2_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/Lab4_V2/Lab4_V2_ooc.xdc
