# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Desktop/RGB_Matrix_constrains.xdc

# Block Designs: bd/Lab3/Lab3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab3 || ORIG_REF_NAME==Lab3} -quiet] -quiet

# IP: bd/Lab3/ip/Lab3_blk_mem_gen_0_0/Lab3_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab3_blk_mem_gen_0_0 || ORIG_REF_NAME==Lab3_blk_mem_gen_0_0} -quiet] -quiet

# XDC: bd/Lab3/Lab3_ooc.xdc
