# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/Lab5_axi_smc_0.xci
# IP: The module: 'Lab5_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/bd_73ec.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_0/bd_73ec_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_1/bd_73ec_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_2/bd_73ec_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_3/bd_73ec_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_4/bd_73ec_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_5/bd_73ec_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_6/bd_73ec_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_7/bd_73ec_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_8/bd_73ec_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_9/bd_73ec_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_10/bd_73ec_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_11/bd_73ec_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_12/bd_73ec_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_1/bd_73ec_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_1/bd_73ec_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_5/bd_73ec_s00a2s_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_6/bd_73ec_sarn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_7/bd_73ec_srn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_8/bd_73ec_sawn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_9/bd_73ec_swn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_10/bd_73ec_sbn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_11/bd_73ec_m00s2a_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab5_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/Lab5_axi_smc_0.xci
# IP: The module: 'Lab5_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/bd_73ec.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_0/bd_73ec_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_1/bd_73ec_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_2/bd_73ec_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_3/bd_73ec_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_4/bd_73ec_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_5/bd_73ec_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_6/bd_73ec_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_7/bd_73ec_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_8/bd_73ec_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_9/bd_73ec_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_10/bd_73ec_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_11/bd_73ec_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_12/bd_73ec_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_1/bd_73ec_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_1/bd_73ec_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_5/bd_73ec_s00a2s_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_6/bd_73ec_sarn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_7/bd_73ec_srn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_8/bd_73ec_sawn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_9/bd_73ec_swn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_10/bd_73ec_sbn_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/bd_0/ip/ip_11/bd_73ec_m00s2a_0_ooc.xdc

# XDC: /home/sebastian/Desktop/Git/EmbeddedSystems/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab5_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
