# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/RGB_Matrix.xdc

# Block Designs: bd/Lab6/Lab6.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab6 || ORIG_REF_NAME==Lab6} -quiet] -quiet

# IP: bd/Lab6/ip/Lab6_processing_system7_0_0/Lab6_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab6_processing_system7_0_0 || ORIG_REF_NAME==Lab6_processing_system7_0_0} -quiet] -quiet

# IP: bd/Lab6/ip/Lab6_blk_mem_gen_0_0/Lab6_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab6_blk_mem_gen_0_0 || ORIG_REF_NAME==Lab6_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/Lab6/ip/Lab6_axi_bram_ctrl_0_0/Lab6_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab6_axi_bram_ctrl_0_0 || ORIG_REF_NAME==Lab6_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/Lab6/ip/Lab6_xadc_wiz_0_0/Lab6_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab6_xadc_wiz_0_0 || ORIG_REF_NAME==Lab6_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/Lab6/ip/Lab6_axi_smc_0/Lab6_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab6_axi_smc_0 || ORIG_REF_NAME==Lab6_axi_smc_0} -quiet] -quiet

# IP: bd/Lab6/ip/Lab6_rst_ps7_0_100M_0/Lab6_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab6_rst_ps7_0_100M_0 || ORIG_REF_NAME==Lab6_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/Lab6/Lab6_ooc.xdc
