# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/RGB_Matrix.xdc

# Block Designs: bd/IndividualProject/IndividualProject.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IndividualProject || ORIG_REF_NAME==IndividualProject} -quiet] -quiet

# IP: bd/IndividualProject/ip/IndividualProject_processing_system7_0_0/IndividualProject_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IndividualProject_processing_system7_0_0 || ORIG_REF_NAME==IndividualProject_processing_system7_0_0} -quiet] -quiet

# IP: bd/IndividualProject/ip/IndividualProject_axi_bram_ctrl_0_0/IndividualProject_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IndividualProject_axi_bram_ctrl_0_0 || ORIG_REF_NAME==IndividualProject_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/IndividualProject/ip/IndividualProject_blk_mem_gen_0_0/IndividualProject_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IndividualProject_blk_mem_gen_0_0 || ORIG_REF_NAME==IndividualProject_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/IndividualProject/ip/IndividualProject_rst_ps7_0_100M_0/IndividualProject_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IndividualProject_rst_ps7_0_100M_0 || ORIG_REF_NAME==IndividualProject_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/IndividualProject/ip/IndividualProject_axi_smc_0/IndividualProject_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IndividualProject_axi_smc_0 || ORIG_REF_NAME==IndividualProject_axi_smc_0} -quiet] -quiet

# IP: bd/IndividualProject/ip/IndividualProject_xadc_wiz_0_1/IndividualProject_xadc_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IndividualProject_xadc_wiz_0_1 || ORIG_REF_NAME==IndividualProject_xadc_wiz_0_1} -quiet] -quiet

# IP: bd/IndividualProject/ip/IndividualProject_axi_gpio_0_2/IndividualProject_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IndividualProject_axi_gpio_0_2 || ORIG_REF_NAME==IndividualProject_axi_gpio_0_2} -quiet] -quiet

# IP: bd/IndividualProject/ip/IndividualProject_axi_gpio_0_3/IndividualProject_axi_gpio_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IndividualProject_axi_gpio_0_3 || ORIG_REF_NAME==IndividualProject_axi_gpio_0_3} -quiet] -quiet

# IP: bd/IndividualProject/ip/IndividualProject_blk_mem_gen_0_1/IndividualProject_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IndividualProject_blk_mem_gen_0_1 || ORIG_REF_NAME==IndividualProject_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/IndividualProject/ip/IndividualProject_axi_bram_ctrl_0_1/IndividualProject_axi_bram_ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IndividualProject_axi_bram_ctrl_0_1 || ORIG_REF_NAME==IndividualProject_axi_bram_ctrl_0_1} -quiet] -quiet

# XDC: bd/IndividualProject/IndividualProject_ooc.xdc
