# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.cache/wt [current_project]
set_property parent.project_path /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:2.0 [current_project]
set_property ip_output_repo /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/hdl/IndividualProject_wrapper.vhd
  /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/imports/new/color_channel.vhd
  /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/imports/new/pwm_generator.vhd
  /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/imports/new/row.vhd
  /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/imports/new/timer.vhd
  /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/imports/new/top.vhd
}
add_files /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/IndividualProject.bd
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_processing_system7_0_0/IndividualProject_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_bram_ctrl_0_0/IndividualProject_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_blk_mem_gen_0_0/IndividualProject_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_rst_ps7_0_100M_0/IndividualProject_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_rst_ps7_0_100M_0/IndividualProject_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_rst_ps7_0_100M_0/IndividualProject_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_1/bd_8718_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_1/bd_8718_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_2/bd_8718_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_3/bd_8718_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_4/bd_8718_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_5/bd_8718_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_6/bd_8718_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_10/bd_8718_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_11/bd_8718_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_12/bd_8718_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_13/bd_8718_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_14/bd_8718_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_15/bd_8718_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_16/bd_8718_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_17/bd_8718_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_18/bd_8718_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_19/bd_8718_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_20/bd_8718_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_21/bd_8718_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_23/bd_8718_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_24/bd_8718_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_25/bd_8718_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_26/bd_8718_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_27/bd_8718_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_28/bd_8718_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_30/bd_8718_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_31/bd_8718_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_32/bd_8718_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_33/bd_8718_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_34/bd_8718_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_35/bd_8718_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_37/bd_8718_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_38/bd_8718_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_39/bd_8718_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_40/bd_8718_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_41/bd_8718_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_42/bd_8718_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_44/bd_8718_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_45/bd_8718_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_46/bd_8718_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_47/bd_8718_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_48/bd_8718_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_smc_0/bd_0/ip/ip_49/bd_8718_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_xadc_wiz_0_1/IndividualProject_xadc_wiz_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_xadc_wiz_0_1/IndividualProject_xadc_wiz_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_gpio_0_2/IndividualProject_axi_gpio_0_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_gpio_0_2/IndividualProject_axi_gpio_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_gpio_0_2/IndividualProject_axi_gpio_0_2.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_gpio_0_3/IndividualProject_axi_gpio_0_3_board.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_gpio_0_3/IndividualProject_axi_gpio_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_gpio_0_3/IndividualProject_axi_gpio_0_3.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_blk_mem_gen_0_1/IndividualProject_blk_mem_gen_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/ip/IndividualProject_axi_bram_ctrl_0_1/IndividualProject_axi_bram_ctrl_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/sources_1/bd/IndividualProject/IndividualProject_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/constrs_1/imports/new/RGB_Matrix.xdc
set_property used_in_implementation false [get_files /home/sebastian/Desktop/Git/EmbeddedSystems/IndividualProject/IndividualProject.srcs/constrs_1/imports/new/RGB_Matrix.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
